// app/layout.js

import { Inter } from "next/font/google";
import ReduxProvider from './ReduxProvider'; // Assurez-vous que le chemin est correct
import ClientProvider from '../components/ClientProvider'; // Assurez-vous que le chemin est correct
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Renov Habitat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ClientProvider>
            {children}
          </ClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
