// app/layout.js

import ReduxProvider from './ReduxProvider';
import ClientProvider from '../components/ClientProvider';
import './globals.css';

// Pile système — chargement instantané, zéro requête réseau au boot.
const interClassName = "font-sans antialiased";

export const metadata = {
  title: "Renov Habitat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={interClassName}>
        <ReduxProvider>
          <ClientProvider>
            {children}
          </ClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
